--Bai 1
CREATE TABLE BanDoc (
	MaBD NVARCHAR(250) PRIMARY KEY ,
	HoTenBD NVARCHAR(250),
	NgaySinh DATE,
	Lop NVARCHAR(250),
	QueQuan NVARCHAR(250),
	SoDT NVARCHAR(250)
)
--
ALTER TABLE BanDoc
ADD CONSTRAINT Check_NgaySinh CHECK(NgaySinh <GetDate())
-- 
CREATE TABLE SACH(
	MaS NVARCHAR(250)  PRIMARY KEY,
	TheLoai NVARCHAR(250) ,
	TacGia NVARCHAR(250) ,
	NamXB INT ,
	NhaXB NVARCHAR(250)
)
--
CREATE TABLE PhieuMuon(
	MaPhieu INT IDENTITY PRIMARY KEY ,
	MaBD NVARCHAR(250),
	MaS NVARCHAR(250) ,
	NgayMuon DATE ,
	NgayHenTra DATE  ,
	CHECK(DATEDIFF(DAY,NgayMuon,NgayHenTra) <= 5),
	TraSach INT DEFAULT  0,
	CONSTRAINT Check_TraSach CHECK (TraSach =1 OR TraSach = 0),
	CONSTRAINT FK_MaBD FOREIGN KEY (MaBD) REFERENCES BanDoc(MaBD),
	CONSTRAINT FK_Ms FOREIGN KEY (MaS) REFERENCES Sach(Mas),

)
--Bai 2

CREATE TABLE ChuyenBay (
	MaCB CHAR(5) PRIMARY KEY,
	GaDi NVARCHAR(50),
	GaDen NVARCHAR(50) ,
	DoDai INT,
	GioDi TIME,
	GioDen TIME,
	ChiPhi INT
)
--
CREATE TABLE MayBay(
	MaMB NVARCHAR(250) PRIMARY KEY,
	Hieu NVARCHAR(250),
	TamBay INT
)
-- 
CREATE TABLE NhanVien (
	MaNV NVARCHAR(250) PRIMARY KEY,
	Ten NVARCHAR(250),
	Luong INT
)
--
CREATE TABLE ChungNhan (
	MaNV NVARCHAR(250),
	MaMB NVARCHAR(250),
	CONSTRAINT PK_MaChungNhan PRIMARY KEY(MaNV,MaMB)
)

